# Generated by Django 6.0.2 on 2026-02-05 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('quoted', 'Quoted'), ('won', 'Won'), ('lost', 'Lost'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], max_length=64)),
                ('customer_name', models.JSONField(blank=True, default=list)),
                ('customer_email', models.JSONField(blank=True, default=list)),
                ('site_address', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('dates', models.JSONField(blank=True, default=list)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='accounts.account')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('done', 'Done'), ('cancelled', 'Cancelled')], default='pending', max_length=64)),
                ('priority', models.SmallIntegerField(default=1)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='accounts.account')),
                ('email_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='mail.emailmessage')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='jobs.job')),
                ('thread', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='mail.emailthread')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['account', 'status'], name='jobs_job_account_aede7f_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['account'], name='jobs_job_account_0a6d2c_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['account', 'status'], name='jobs_task_account_be5ddc_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['due_at'], name='jobs_task_due_at_8310cf_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['email_message'], name='jobs_task_email_m_a1faba_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['job'], name='jobs_task_job_id_8a9a9a_idx'),
        ),
    ]
