# Generated by Django 6.0.2 on 2026-02-11 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_make_account_task_number_required'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='task',
            new_name='jobs_task_account_c2a8ff_idx',
            old_name='jobs_task_account_ta_123456_idx',
        ),
    ]
