# Generated by Django 6.0.2 on 2026-02-05 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('gmail', 'Gmail'), ('microsoft', 'Microsoft')], max_length=32)),
                ('email', models.EmailField(max_length=255)),
                ('signature_html', models.TextField(blank=True, null=True)),
                ('writing_style', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['provider', 'email'],
                'indexes': [models.Index(fields=['provider', 'email'], name='accounts_ac_provide_e7555e_idx')],
                'unique_together': {('provider', 'email')},
            },
        ),
    ]
