# Generated by Django 6.0.2 on 2026-02-10 22:44

from django.conf import settings
from django.db import migrations, models


def populate_account_users(apps, schema_editor):
    """Populate the users ManyToMany field for existing accounts based on email matching"""
    Account = apps.get_model('accounts', 'Account')
    User = apps.get_model(settings.AUTH_USER_MODEL)
    
    for account in Account.objects.all():
        # Find users with matching email
        matching_users = User.objects.filter(email=account.email)
        if matching_users.exists():
            account.users.set(matching_users)


def reverse_populate(apps, schema_editor):
    """Reverse migration - clear users from accounts"""
    Account = apps.get_model('accounts', 'Account')
    for account in Account.objects.all():
        account.users.clear()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_oauthtoken_scopes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='users',
            field=models.ManyToManyField(blank=True, help_text='Users who have access to this account', related_name='accounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(populate_account_users, reverse_populate),
    ]
