# Generated by Django 6.0.2 on 2026-02-05 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('function', models.CharField(max_length=64)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='accounts.account')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('prompt', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='accounts.account')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('account', 'name')},
            },
        ),
        migrations.CreateModel(
            name='EmailLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='mail.emailmessage')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_labels', to='automation.label')),
            ],
            options={
                'indexes': [models.Index(fields=['label'], name='automation__label_i_59029e_idx'), models.Index(fields=['email_message'], name='automation__email_m_741a86_idx')],
                'unique_together': {('email_message', 'label')},
            },
        ),
        migrations.CreateModel(
            name='LabelAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='label_links', to='automation.action')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='automation.label')),
            ],
            options={
                'ordering': ['order'],
                'indexes': [models.Index(fields=['label', 'order'], name='automation__label_i_80984a_idx')],
                'unique_together': {('label', 'action')},
            },
        ),
    ]
