# Generated by Django 6.0.2 on 2026-02-05 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_message_id', models.CharField(max_length=255)),
                ('subject', models.CharField(blank=True, max_length=512, null=True)),
                ('from_address', models.CharField(max_length=255)),
                ('from_name', models.CharField(blank=True, max_length=255, null=True)),
                ('to_addresses', models.JSONField(default=list)),
                ('cc_addresses', models.JSONField(blank=True, default=list, null=True)),
                ('bcc_addresses', models.JSONField(blank=True, default=list, null=True)),
                ('date_sent', models.DateTimeField(blank=True, null=True)),
                ('body_html', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_messages', to='accounts.account')),
            ],
            options={
                'ordering': ['-date_sent', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Draft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_draft_id', models.CharField(blank=True, max_length=255, null=True)),
                ('to_addresses', models.JSONField(blank=True, default=list)),
                ('cc_addresses', models.JSONField(blank=True, default=list)),
                ('bcc_addresses', models.JSONField(blank=True, default=list)),
                ('subject', models.CharField(blank=True, max_length=512, null=True)),
                ('body_html', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drafts', to='accounts.account')),
                ('email_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drafts', to='mail.emailmessage')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_thread_id', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_threads', to='accounts.account')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='mail.emailthread'),
        ),
        migrations.CreateModel(
            name='DraftAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=128)),
                ('size_bytes', models.PositiveIntegerField()),
                ('content', models.BinaryField(blank=True, null=True)),
                ('storage_path', models.CharField(blank=True, max_length=1024, null=True)),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='mail.draft')),
            ],
            options={
                'indexes': [models.Index(fields=['draft'], name='mail_drafta_draft_i_d09617_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='draft',
            index=models.Index(fields=['account', 'external_draft_id'], name='mail_draft_account_79ffd3_idx'),
        ),
        migrations.AddIndex(
            model_name='draft',
            index=models.Index(fields=['email_message'], name='mail_draft_email_m_ddf072_idx'),
        ),
        migrations.AddIndex(
            model_name='emailthread',
            index=models.Index(fields=['account', 'external_thread_id'], name='mail_emailt_account_aabb9e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='emailthread',
            unique_together={('account', 'external_thread_id')},
        ),
        migrations.AddIndex(
            model_name='emailmessage',
            index=models.Index(fields=['account', 'external_message_id'], name='mail_emailm_account_728347_idx'),
        ),
        migrations.AddIndex(
            model_name='emailmessage',
            index=models.Index(fields=['account', 'date_sent'], name='mail_emailm_account_c15d42_idx'),
        ),
        migrations.AddIndex(
            model_name='emailmessage',
            index=models.Index(fields=['account', 'from_address'], name='mail_emailm_account_1ba137_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='emailmessage',
            unique_together={('account', 'external_message_id')},
        ),
    ]
