# Generated by Django 5.1 on 2026-02-28 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mail", "0002_syncrun"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider_attachment_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("filename", models.CharField(blank=True, default="", max_length=255)),
                (
                    "content_type",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("size_bytes", models.PositiveIntegerField(default=0)),
                ("is_inline", models.BooleanField(default=False)),
                ("content_id", models.CharField(blank=True, max_length=255, null=True)),
                ("content", models.BinaryField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["filename", "pk"],
            },
        ),
        migrations.AddField(
            model_name="emailattachment",
            name="email_message",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attachments",
                to="mail.emailmessage",
            ),
        ),
        migrations.AddIndex(
            model_name="emailattachment",
            index=models.Index(
                fields=["email_message"], name="mail_emaila_email_m_c62e1f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emailattachment",
            index=models.Index(
                fields=["provider_attachment_id"], name="mail_emaila_provide_698de9_idx"
            ),
        ),
    ]
