# Generated by Django 5.1

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mail", "0003_emailattachment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailattachment",
            name="filename",
            field=models.CharField(blank=True, default="", max_length=1024),
        ),
    ]
